### ISSUE TITLE
Parsing in quote tags

### ISSUE THREAD

**Issue by C1n** [s9e/phpbb-ext-mediaembed#4]
Not as much an issue as it is a question but is there a way to hide the parsed content in quotes? 

As an example, I have a topic on my forum where users post a lot of youtube videos. One user posts 5 videos that are quoted by another and suddenly the post becomes very long since all the quoted youtube links are also parsed.

I'd like the option to hide it but I don't know if that is possible or - if not  - is something you can easily integrate.

**Comment by JoshyPHP** [comment]
The embedded content uses a `data-s9e-mediaembed` attributes that  you can use in a CSS selector. For example:

``` css
blockquote [data-s9e-mediaembed]
{
    max-width:  240px !important;
    max-height: 135px !important;
}
```
